# stage 1: build go
FROM golang:1.12 as go-builder

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN rm -fr ./dist && mkdir ./dist
RUN cp ./config/prod.yml ./dist/config.yml
RUN GOARCH=amd64 CGO_ENABLED=0 GOOS=linux make build

# stage 3: run
FROM alpine:latest

WORKDIR /app

EXPOSE 9000

ENV PUSHAAS_ENV=prod
ENV PUSHAAS_CONFIG="./config.yml"

COPY --from=go-builder /app/dist/pushaas ./pushaas
# TODO review this "config.yml", doesn't seem right
COPY --from=go-builder /app/config/prod.yml ./config.yml

# TODO pass AWS environment variables
# TODO pass basic auth environment variables
ENTRYPOINT ["/app/pushaas"]
