FROM golang:1.12

ENV GO111MODULE=on

WORKDIR /app

# cache go modules
COPY go.mod .
COPY go.sum .
RUN go mod download

EXPOSE 9000

COPY . .

ENV PUSHAPI_PUSH_STREAM__URL http://push-stream:9080
ENV PUSHAPI_REDIS__URL redis://push-redis:6379

CMD ["go", "run", "main.go"]
